PIDs:
  X:
    kp: 20.0
    kd: 10.0
    ki: 0.1
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    kp: 20.0
    kd: 10.0
    ki: 0.1
    minOutput: -10.0
    maxOutput: 10.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: -40000.0
    kd: -10000.0
    ki: -6000.0
    minOutput: -10000.0
    maxOutput: 10000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
  Yaw:
    kp: 500.0
    kd: 100.0
    ki: 0.1
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
